spring.application.name=spacework-backend

# puerto del servidor local
server.port=8080

# conexion a la base de datos sql server local
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SpaceWork;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Klinzxd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# config de hibernate para que no borre las tablas y muestre el sql en consola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# datos del correo (usando gmail por ahora para pruebas)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pruebas.spacework@gmail.com
spring.mail.password=password_smtp_app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.error.include-message=always
server.error.include-stacktrace=always
